//
// Created by Даниил on 06.04.2022.
//

#ifndef STEP_SETTINGS_H
#define STEP_SETTINGS_H

#define WINDOW_WIDTH 1280
#define WINDOW_HEIGHT 768

#define WINDOW_CELL_SIDE 32

#define CELL_HORIZONTAL_COUNT 40
#define CELL_VERTICAL_COUNT 24

#endif //STEP_SETTINGS_H
